import type { Driver } from "@/types/driver";
import { getDriverSafetyClearance } from "@/types/driver";

export const MOCK_DRIVERS: Driver[] = [
  {
    id: "d1",
    name: "Alex Kumar",
    licenceNumber: "DL-88213",
    licenceCategory: "LMV",
    licenceExpiry: "2027-08-01",
    contactNumber: "+91 98765 43210",
    tripCompletionPercent: 96,
    safetyScore: 92,
    safetyClearance: getDriverSafetyClearance("AVAILABLE"),
    status: "AVAILABLE",
  },
  {
    id: "d2",
    name: "John",
    licenceNumber: "DL-99102",
    licenceCategory: "HMV",
    licenceExpiry: "2025-03-01",
    contactNumber: "+91 98220 11223",
    tripCompletionPercent: 81,
    safetyScore: 60,
    safetyClearance: getDriverSafetyClearance("SUSPENDED"),
    status: "SUSPENDED",
  },
  {
    id: "d3",
    name: "Priya",
    licenceNumber: "DL-11023",
    licenceCategory: "LMV",
    licenceExpiry: "2026-11-01",
    contactNumber: "+91 90000 44556",
    tripCompletionPercent: 99,
    safetyScore: 88,
    safetyClearance: getDriverSafetyClearance("ON_TRIP"),
    status: "ON_TRIP",
  },
  {
    id: "d4",
    name: "Suresh",
    licenceNumber: "DL-44551",
    licenceCategory: "HMV",
    licenceExpiry: "2028-01-01",
    contactNumber: "+91 98888 66554",
    tripCompletionPercent: 74,
    safetyScore: 85,
    safetyClearance: getDriverSafetyClearance("OFF_DUTY"),
    status: "OFF_DUTY",
  },
];
