import type { Vehicle } from "@/types/vehicle";

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: "v1",
    registrationNumber: "MH-12-AB-4521",
    make: "Tata",
    model: "LPT 1613",
    type: "TRUCK",
    capacityKg: 12000,
    odometerKm: 145230,
    status: "ON_TRIP",
  },
  {
    id: "v2",
    registrationNumber: "DL-01-CD-8834",
    make: "Ashok Leyland",
    model: "Boss 1415",
    type: "TRUCK",
    capacityKg: 10000,
    odometerKm: 98210,
    status: "AVAILABLE",
  },
  {
    id: "v3",
    registrationNumber: "KA-05-EF-2210",
    make: "Mahindra",
    model: "Blazo X 35",
    type: "TRUCK",
    capacityKg: 15000,
    odometerKm: 201450,
    status: "IN_SHOP",
  },
  {
    id: "v4",
    registrationNumber: "TN-09-GH-6677",
    make: "Force",
    model: "Traveller",
    type: "VAN",
    capacityKg: 1200,
    odometerKm: 67800,
    status: "AVAILABLE",
  },
  {
    id: "v5",
    registrationNumber: "GJ-06-IJ-3344",
    make: "Eicher",
    model: "Pro 3015",
    type: "TRUCK",
    capacityKg: 11000,
    odometerKm: 178900,
    status: "AVAILABLE",
  },
  {
    id: "v6",
    registrationNumber: "RJ-14-KL-9901",
    make: "Volvo",
    model: "FM 420",
    type: "TRUCK",
    capacityKg: 20000,
    odometerKm: 312000,
    status: "RETIRED",
  },
  {
    id: "v7",
    registrationNumber: "UP-32-MN-1188",
    make: "Tata",
    model: "Starbus",
    type: "BUS",
    capacityKg: 8000,
    odometerKm: 89000,
    status: "ON_TRIP",
  },
  {
    id: "v8",
    registrationNumber: "WB-19-OP-5566",
    make: "BharatBenz",
    model: "1217C",
    type: "TRUCK",
    capacityKg: 9000,
    odometerKm: 134500,
    status: "AVAILABLE",
  },
];
