import type { Vehicle } from "@/types/vehicle";

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: "v1",
    registrationNumber: "GJ01AB452",
    name: "VAN-05",
    model: "VAN-05",
    type: "VAN",
    typeLabel: "Van",
    capacityLabel: "500 kg",
    odometerKm: 74000,
    acquisitionCost: 620000,
    status: "AVAILABLE",
  },
  {
    id: "v2",
    registrationNumber: "GJ01AB998",
    name: "TRUCK-11",
    model: "TRUCK-11",
    type: "TRUCK",
    typeLabel: "Truck",
    capacityLabel: "5 Ton",
    odometerKm: 182000,
    acquisitionCost: 2450000,
    status: "ON_TRIP",
  },
  {
    id: "v3",
    registrationNumber: "GJ01AB1120",
    name: "MINI-03",
    model: "MINI-03",
    type: "TRUCK",
    typeLabel: "Mini",
    capacityLabel: "1 Ton",
    odometerKm: 66000,
    acquisitionCost: 410000,
    status: "IN_SHOP",
  },
  {
    id: "v4",
    registrationNumber: "GJ01AB008",
    name: "VAN-09",
    model: "VAN-09",
    type: "VAN",
    typeLabel: "Van",
    capacityLabel: "750 kg",
    odometerKm: 241900,
    acquisitionCost: 590000,
    status: "RETIRED",
  },
];
